version: "3.8"

services:
  backend:
    build:
      context: ./backend-flask
    ports:
      - "4567:4567"
    environment:
      CONNECTION_URL: "postgresql://postgres:password@db:5432/cruddur"
      AWS_REGION: "us-east-1"

  frontend:
    build:
      context: ./frontend-react-js
    ports:
      - "3001:3000"

  xray-daemon:
    image: amazon/aws-xray-daemon
    command: ["xray", "-o", "-b", "xray-daemon:2000"]
    ports:
      - "2000:2000/udp"

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cruddur
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  dynamodb-local:
    container_name: aws-bootcamp-cruddur-2023-dynamodb-local
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: aws-bootcamp-cruddur-2023-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

volumes:
  db-data:
  
